# l: Cycle Repeat One -> Repeat All -> None
l cycle-values loop-file "inf" "no" ; cycle-values loop-playlist "inf" "no"

# s: Toggle Shuffle mode (on/off)
s cycle shuffle

# p: Open the interactive Playlist Menu
p script-binding select/select-playlist

# Alt-Gr: Open the interactive Playlist Menu (dmenu-like)
ISO_Level3_Shift script-binding select/select-playlist
