# -*- conf -*-
font=Mononoki:size=13

[colors-dark]
alpha=0.87
background=f9f9f9
foreground=000000

# Normal colors
regular0=000000
regular1=ff004f
regular2=05996b
regular3=bd852b
regular4=f53c3c
regular5=b000b0
regular6=2f7791
regular7=ff004f

# Bright colors
bright0=3d3d3d
bright1=f53c3c
bright2=00ffb0
bright3=ffb37b
bright4=7f052c
bright5=b874b8
bright6=49a1b3
bright7=f83875

# Cursor (text cursor)
cursor=000000 ff004f

# Selection
selection-foreground=f9f9f9
selection-background=ff004f

[text-bindings]
\x1b\x0d=Shift+Return
