# 3-finger swipe up/down -> toggle overview
gesture swipe up 3 niri msg action open-overview
gesture swipe down 3 niri msg action open-overview
gesture pinch in 3 niri msg action open-overview
gesture pinch in 4 niri msg action open-overview
gesture pinch out 3 niri msg action close-overview
gesture pinch out 4 niri msg action close-overview
