# Text / Code
text/plain = org.lite_xl.lite_xl.desktop
text/markdown = org.lite_xl.lite_xl.desktop
text/rust = org.lite_xl.lite_xl.desktop
text/x-python = org.lite_xl.lite_xl.desktop
text/x-python3 = org.lite_xl.lite_xl.desktop
text/x-objcsrc = org.lite_xl.lite_xl.desktop
application/toml = org.lite_xl.lite_xl.desktop
application/json = org.lite_xl.lite_xl.desktop
application/x-desktop = org.lite_xl.lite_xl.desktop
application/x-spss-sav = org.lite_xl.lite_xl.desktop

# Images
image/png = imv-dir.desktop
image/jpeg = imv-dir.desktop
image/gif = imv-dir.desktop
image/webp = imv-dir.desktop
image/bmp = imv-dir.desktop
image/x-bmp = imv-dir.desktop
image/tiff = imv-dir.desktop
image/svg+xml = imv-dir.desktop

# 3D Models
model/stl = userapp-fstl-JB11L3.desktop
application/sla = userapp-fstl-JB11L3.desktop
model/x.stl-ascii = userapp-fstl-JB11L3.desktop
model/x.stl-binary = userapp-fstl-JB11L3.desktop
